language: csharp
dist: xenial
mono: none
dotnet: 3.1.404
install:
  - cd src
  - dotnet restore
  - cd test
  - dotnet restore
script:
  - cd src
  - dotnet build
  - cd test
  - dotnet build
  - dotnet test
