language: csharp
dist: xenial
mono: none
dotnet: 3.1.404
install:
  - cd src
  - dotnet restore
  - cd ../test
  - dotnet restore
  - cd ../
script:
  - dotnet build --configuration Test
  - cd test
  - dotnet test
